name: Build OpenWrt Plugin with SRS

on:
  #schedule:
    #- cron: 0 20 * * *
  release:
    types: [published]
    
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions false true'
        required: false
        default: 'false'
  watch:
    types: [started]
    

permissions:
  contents: read


    
env:
  REPO_URL: https://github.com/openwrt/openwrt
  # 分支版本master例如：openwrt-19.07
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: Lean--p.info
  Firmware_Name: OpenWrt-CI-test
  DIY_P1_SH: smpackage/ddd1.sh
  DIY_P2_SH: smpackage/ddd.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # 确保子模块也被检出

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc unzip zlib1g-dev file wget

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.0

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy plugin source
      run: |
        mkdir -p openwrt/package/srs
        cp -r ./package/srs/* openwrt/package/srs/

    - name: Configure build
      run: |
        cd openwrt
        make defconfig
        make menuconfig

    - name: Build toolchain
      run: |
        cd openwrt
        make toolchain/install

    - name: Build plugin
      run: |
        cd openwrt
        make package/srs/compile V=99

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-plugin
        path: openwrt/bin/packages
